# Generated by Django 4.2.25 on 2025-10-30 18:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=10, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('estimated_gdp', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='RefreshStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
